version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: oniloan
    env_file:
      - ./oniloan/.env
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
